export interface Product {
  id: string
  name: string
  description: string
  category: "Flores Comestibles" | "Brotes" | "Hortalizas y Hojas Verdes"
  image: string
  usage?: string
  flavorProfile?: string
  price: number
}

export const products: Product[] = [
  // Flores Comestibles
  {
    id: "pensamiento",
    name: "Pensamiento",
    description: "Flores vibrantes con un ligero sabor dulce y herbal.",
    usage: "Perfectas para decorar postres, ensaladas y cócteles.",
    category: "Flores Comestibles",
    image: "/edible-pansy-flower.jpg",
    price: 120,
  },
  {
    id: "begonia",
    name: "Begonia",
    description: "Suaves y jugosas, con un toque cítrico refrescante.",
    usage: "Añaden una nota ácida a ensaladas y platos gourmet.",
    category: "Flores Comestibles",
    image: "/edible-begonia-flower.jpg",
    price: 110,
  },
  {
    id: "lavanda",
    name: "Lavanda",
    description: "Aromática y delicada, con notas florales y herbales.",
    usage: "Perfecta para infusiones, repostería y platillos sofisticados.",
    category: "Flores Comestibles",
    image: "/single-lavender-stem.png",
    price: 130,
  },
  {
    id: "flor-cilantro",
    name: "Flor de Cilantro",
    description: "Sabor suave y fresco con un ligero toque a cilantro.",
    usage: "Ideal para decorar sopas, ceviches y ensaladas.",
    category: "Flores Comestibles",
    image: "/cilantro-flower.jpg",
    price: 90,
  },
  {
    id: "flor-hinojo",
    name: "Flor de Hinojo",
    description: "Aromática y ligeramente anisada.",
    usage: "Perfecta para pescados, carnes y postres.",
    category: "Flores Comestibles",
    image: "/fennel-flower.jpg",
    price: 95,
  },
  {
    id: "clavelina",
    name: "Clavelina",
    description: "Pétalos coloridos con un toque especiado y sutilmente dulce.",
    usage: "Ideales para repostería y bebidas.",
    category: "Flores Comestibles",
    image: "/dianthus-flower.jpg",
    price: 105,
  },
  {
    id: "flor-sauco",
    name: "Flor de Sauco",
    description: "Notas florales y dulces con un toque cítrico.",
    usage: "Excelente para jarabes, infusiones y cócteles.",
    category: "Flores Comestibles",
    image: "/elderflower.jpg",
    price: 115,
  },
  {
    id: "bugambilia",
    name: "Flor de Bugambilia",
    description: "Pétalos vibrantes con un toque terroso y herbal.",
    usage: "Tradicional en infusiones y decoraciones.",
    category: "Flores Comestibles",
    image: "/bougainvillea-flower.jpg",
    price: 85,
  },
  {
    id: "aretillos",
    name: "Flores Aretillos",
    description: "Flores llamativas con notas florales y un ligero dulzor.",
    usage: "Ideales para platos gourmet.",
    category: "Flores Comestibles",
    image: "/fuchsia-flower.jpg",
    price: 125,
  },
  {
    id: "capuchina",
    name: "Flor Capuchina",
    description: "Pétalos de colores vivos con un sabor picante similar al rábano.",
    usage: "Ideales para ensaladas y platos frescos.",
    category: "Flores Comestibles",
    image: "/single-nasturtium.png",
    price: 100,
  },
  {
    id: "rosas-miniatura",
    name: "Rosas Miniatura",
    description: "Elegantes y aromáticas, con un delicado sabor floral.",
    usage: "Usadas en repostería, infusiones y platos gourmet.",
    category: "Flores Comestibles",
    image: "/miniature-roses.jpg",
    price: 140,
  },
  {
    id: "borraja",
    name: "Flor de Borraja",
    description: "Azules y delicadas, con un ligero sabor a pepino.",
    usage: "Perfectas para ensaladas y bebidas refrescantes.",
    category: "Flores Comestibles",
    image: "/borage-flower.jpg",
    price: 110,
  },

  // Brotes
  {
    id: "brote-cilantro",
    name: "Brote de Cilantro",
    description: "Sabor fresco y más intenso que las hojas maduras.",
    usage: "Ideal para guacamole, tacos y ensaladas.",
    category: "Brotes",
    image: "/cilantro-microgreen.jpg",
    price: 80,
  },
  {
    id: "brote-chicharo",
    name: "Brote de Chícharo",
    description: "Dulce y crujiente, con un toque fresco similar al de los guisantes tiernos.",
    usage: "Excelente para ensaladas y woks.",
    category: "Brotes",
    image: "/pea-shoot.jpg",
    price: 85,
  },
  {
    id: "brote-rabano",
    name: "Brote de Rábano",
    description: "Picante y vibrante, con un ligero toque especiado.",
    usage: "Perfecto para darle intensidad a sándwiches y tacos.",
    category: "Brotes",
    image: "/radish-microgreen.jpg",
    price: 80,
  },
  {
    id: "brote-amaranto",
    name: "Brote de Amaranto",
    description: "Hojas pequeñas con un sabor terroso y un alto contenido de nutrientes.",
    usage: "Ideales para ensaladas y platillos saludables.",
    category: "Brotes",
    image: "/amaranth-microgreen.jpg",
    price: 90,
  },
  {
    id: "brote-arugula",
    name: "Brote de Arúgula",
    description: "Intenso y picante, con un toque a nuez.",
    usage: "Aporta carácter a ensaladas y pizzas.",
    category: "Brotes",
    image: "/arugula-microgreen.jpg",
    price: 85,
  },
  {
    id: "brote-betabel",
    name: "Brote de Betabel",
    description: "Hojas pequeñas con un sutil dulzor terroso y vibrante color rojo.",
    usage: "Aporta color y sabor a ensaladas y bowls.",
    category: "Brotes",
    image: "/placeholder.svg?height=400&width=400",
    price: 95,
  },
  {
    id: "brote-maiz",
    name: "Brote de Maíz",
    description: "Dulce y jugoso, con un toque crujiente.",
    usage: "Perfecto para ensaladas y guarniciones frescas.",
    category: "Brotes",
    image: "/placeholder.svg?height=400&width=400",
    price: 100,
  },
  {
    id: "brote-perejil",
    name: "Brote de Perejil",
    description: "Sabor intenso y fresco.",
    usage: "Aporta un toque herbal a cualquier platillo.",
    category: "Brotes",
    image: "/placeholder.svg?height=400&width=400",
    price: 80,
  },
  {
    id: "brote-albahaca",
    name: "Brote de Albahaca",
    description: "Aromático y con notas frescas.",
    usage: "Perfecto para pizzas, pastas y ensaladas.",
    category: "Brotes",
    image: "/placeholder.svg?height=400&width=400",
    price: 90,
  },
  {
    id: "brote-melon",
    name: "Brote de Melón",
    description: "Dulce y refrescante, con un aroma frutal ligero.",
    usage: "Excelente en ensaladas y decoraciones.",
    category: "Brotes",
    image: "/placeholder.svg?height=400&width=400",
    price: 95,
  },
  {
    id: "brote-menta",
    name: "Brote de Menta",
    description: "Fresco y vibrante, con notas refrescantes.",
    usage: "Ideal para bebidas, postres y ensaladas.",
    category: "Brotes",
    image: "/placeholder.svg?height=400&width=400",
    price: 85,
  },
  {
    id: "brote-zanahoria",
    name: "Brote de Zanahoria",
    description: "Sabor herbáceo con un ligero dulzor.",
    usage: "Ideal para sopas, ensaladas y platos decorativos.",
    category: "Brotes",
    image: "/placeholder.svg?height=400&width=400",
    price: 85,
  },
  {
    id: "oxalis",
    name: "Oxális / Trébol Rojo",
    description: "Ligeramente dulce y terroso, con propiedades nutritivas.",
    usage: "Perfecto para ensaladas y bowls saludables.",
    category: "Brotes",
    image: "/placeholder.svg?height=400&width=400",
    price: 110,
  },
  {
    id: "hoja-amaranto",
    name: "Hoja de Amaranto",
    description: "Terrosa y nutritiva.",
    usage: "Ideal para platillos tradicionales y ensaladas.",
    category: "Brotes",
    image: "/placeholder.svg?height=400&width=400",
    price: 85,
  },
  {
    id: "hoja-sorrel",
    name: "Hoja de Sorrel / Acedera",
    description: "Ácida y refrescante, con un sabor similar al limón.",
    usage: "Perfecta para ensaladas, salsas y pescados.",
    category: "Brotes",
    image: "/placeholder.svg?height=400&width=400",
    price: 95,
  },
  {
    id: "hoja-shizo",
    name: "Hoja de Shizo",
    description: "Exótica y aromática, con un toque cítrico y especiado.",
    usage: "Usada en la cocina japonesa para sushi y ensaladas.",
    category: "Brotes",
    image: "/placeholder.svg?height=400&width=400",
    price: 120,
  },

  // Hortalizas y Hojas Verdes
  {
    id: "arugula",
    name: "Arúgula",
    description: "Hojas de sabor intenso y ligeramente picante, con un toque a nuez.",
    usage: "Perfecta para ensaladas, pizzas y acompañamientos frescos.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 60,
  },
  {
    id: "albahaca-italiana",
    name: "Albahaca Italiana",
    description: "Aromática y fresca, con notas dulces y especiadas.",
    usage: "Esencial en la cocina mediterránea, perfecta para pestos, ensaladas y salsas.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 65,
  },
  {
    id: "albahaca-morada",
    name: "Albahaca Morada",
    description: "Variedad vibrante con hojas de color púrpura y un sabor más especiado.",
    usage: "Ideal para platos asiáticos y decoraciones sofisticadas.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 70,
  },
  {
    id: "kale",
    name: "Berza / Kale",
    description: "Hojas rizadas y robustas, ricas en nutrientes y con un sabor ligeramente terroso.",
    usage: "Excelente para smoothies, ensaladas o salteados.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 55,
  },
  {
    id: "espinaca-baby",
    name: "Espinaca Baby",
    description: "Hojas pequeñas, tiernas y dulces, con un alto contenido de hierro y antioxidantes.",
    usage: "Perfectas para ensaladas, batidos y platillos saludables.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 50,
  },
  {
    id: "arugula-baby",
    name: "Arúgula Baby",
    description: "Versión más tierna y suave de la arúgula tradicional.",
    usage: "Ideal para ensaladas y platos gourmet.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 65,
  },
  {
    id: "bulbo-hinojo",
    name: "Bulbo de Hinojo",
    description: "Crujiente y con un delicado sabor anisado.",
    usage: "Ideal para ensaladas frescas, asados o como base para salsas aromáticas.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 75,
  },
  {
    id: "pak-choi",
    name: "Pak Choi",
    description: "Variedad pequeña del bok choi, con tallos verdes, con un sabor más tierno.",
    usage: "Ideal para guarniciones, woks y platos al vapor.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 60,
  },
  {
    id: "chicharo-japones",
    name: "Chícharo Japonés",
    description: "Vainas tiernas y dulces que pueden comerse enteras.",
    usage: "Perfectas para ensaladas, salteados y platillos orientales.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 80,
  },
  {
    id: "cebollin",
    name: "Cebollín",
    description: "Tallos delgados y frescos con un sabor suave a cebolla.",
    usage: "Ideales para decorar platos, hacer salsas o realzar el sabor.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 45,
  },
  {
    id: "perejil-chino",
    name: "Perejil Chino",
    description: "Más intenso que el común, con un toque cítrico y ligeramente picante.",
    usage: "Perfecto para decorar salsas, ceviches y platos asiáticos.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 55,
  },
  {
    id: "bok-choi",
    name: "Bok Choi",
    description: "Col china de hojas verdes y tallos blancos jugosos.",
    usage: "Perfecto para salteados, sopas y platos asiáticos.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 60,
  },
  {
    id: "betabel-candy",
    name: "Betabel Candy",
    description: "Remolacha de coloración veteada en tonos rosados y blancos.",
    usage: "Ideal para ensaladas y platillos decorativos.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 50,
  },
  {
    id: "rabano-sandia",
    name: "Rábano Sandía",
    description: "Exterior blanco y centro rosa vibrante, con un sabor suave.",
    usage: "Aporta color y textura a ensaladas y platos frescos.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 55,
  },
  {
    id: "zanahoria-baby",
    name: "Zanahoria Baby con Rabo",
    description: "Pequeñas, dulces y crujientes, conservan su tallo verde.",
    usage: "Perfectas para platos gourmet.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 65,
  },
  {
    id: "radicchio",
    name: "Lechuga Radicchio",
    description: "Hojas de un intenso color morado con un sabor ligeramente amargo.",
    usage: "Aporta contraste de color y sabor en ensaladas.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 70,
  },
  {
    id: "lechuga-francesa",
    name: "Lechuga Francesa",
    description: "Hojas tiernas, mantecosas y de sabor suave.",
    usage: "Ideal para ensaladas delicadas, wraps y acompañamientos ligeros.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 50,
  },
  {
    id: "betabel-amarillo",
    name: "Betabel Amarillo / Dorado",
    description: "Sabor más suave y menos terroso que el tradicional.",
    usage: "Perfecto para asados, ensaladas y platos coloridos.",
    category: "Hortalizas y Hojas Verdes",
    image: "/placeholder.svg?height=400&width=400",
    price: 50,
  },
]
